# -*- coding: utf-8 -*-
"""Unemployment Analysis with Python - task 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gllMh3Ug3tvOlZ6mKcaNGKIiP53-ZATU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data1 = pd.read_csv("Unemployment in India.csv")

data1.head()

data1.tail()

data1.info()

data1.isnull().sum()



# cleaned data

data1.dropna(axis = 0, inplace = True)

data1.isnull().sum()

data1.info()

# reset the index

data1.reset_index(inplace=True)

data1.info()

# drop rows from 359 to

data1.iat[739,1]



print(data1["Region"].value_counts())

# column chart to show unemployment rate state wise


plt.figure(figsize=(15, 11))

sns.barplot(data = data1, x = "Region", y = " Estimated Unemployment Rate (%)")
plt.xticks(rotation=45)


plt.tight_layout()
plt.show()

# top 5 region has highest unemployment rate:

top5_states = (
    data1.groupby("Region")[" Estimated Unemployment Rate (%)"]
    .mean()
    .sort_values(ascending=False)
    .head(5)
)

print(top5_states)

fig, ax = plt.subplots(figsize=(8, 5))
sns.barplot(
    x=top5_states.values,
    y=top5_states.index,
    ax=ax
)

ax.set_xlabel("Estimated Unemployment Rate (%)")
ax.set_ylabel("State")
ax.set_title("Top 5 States with Highest Unemployment Rate")
plt.tight_layout()
plt.show()

# pie for unemployment rate by Area Rural or Urban:

area_unemp = (
    data1.groupby("Area")[" Estimated Unemployment Rate (%)"]
    .mean()
)
print(area_unemp)

plt.figure(figsize=(6, 6))
plt.pie(
    area_unemp.values,
    labels=area_unemp.index,
    autopct="%1.1f%%",
    startangle=90
)
plt.title("Average Unemployment Rate by Area")
plt.axis("equal")   # for makes circle perfect
plt.show()

# line graph to monthly unemployment rate:

data1["Date"] = pd.to_datetime(data1[" Date"])

monthly_unemp = (
    data1.groupby("Date")[" Estimated Unemployment Rate (%)"]
    .mean()
    .reset_index()
)

print(monthly_unemp)

fig, ax = plt.subplots(figsize=(10, 5))

sns.lineplot(
    data=monthly_unemp,
    x="Date",
    y=" Estimated Unemployment Rate (%)",
    marker="o",
    ax=ax
)

ax.set_xlabel("Month")
ax.set_ylabel("Estimated Unemployment Rate (%)")
ax.set_title("Monthly Unemployment Rate Trend")
plt.tight_layout()
plt.show()



data2 = pd.read_csv("Unemployment_Rate_upto_11_2020.csv")

data2.head()

data2.info()

area_monthly = (
    data1.groupby([" Date", "Area"])[" Estimated Unemployment Rate (%)"]
    .mean()
    .reset_index()
)

print(area_monthly)

plt.figure(figsize=(15, 5))
sns.lineplot(
    data=area_monthly,
    x=" Date",
    y=" Estimated Unemployment Rate (%)",
    hue="Area"
)
plt.title("Monthly Unemployment Rate by Area")
plt.tight_layout()
plt.show()



